# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array

## NumPy Array Attributes

First let's discuss some useful array attributes.

In [1]:
import numpy as np

x1 = np.array([5, 0, 3, 3, 7, 9])
x1

array([5, 0, 3, 3, 7, 9])

In [2]:
x2 = np.array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [3]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


Another useful attribute is the ``dtype``, the data type of the array:

In [4]:
print("dtype:", x2.dtype)

dtype: int32


some useful functions are ``zeros``, ``ones``, ``eye``.

In [5]:
# create an np array of all zeros
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [6]:
# create an np array of all ones
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# create an identity matrix
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]

5

In [10]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [11]:
x1[-1]

9

In [12]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [13]:
x2 = np.array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[0, 0]

3

In [15]:
x2[2, 0]

1

In [16]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [17]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [18]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [21]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [23]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [24]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [25]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [27]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [29]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [30]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [31]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [32]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [33]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [34]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [35]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [36]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [37]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [38]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x2.shape

(3, 4)

In [40]:
# flatten the two dimentional data to 1-dimention
x2.ravel()

array([12,  5,  2,  4,  7,  6,  8,  8,  1,  6,  7,  7])

# The Basics of Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.

In [41]:
# importing the library
import pandas as pd

In [42]:
# read_csv is an function to read csv files and do operations on it.
dataframe = pd.read_csv("Data.csv")

In [43]:
dataframe

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [44]:
# displaying the columns name
dataframe.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [45]:
# indexing using column name
dataframe["Country"]

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [46]:
# dataframe["Country", "Age"]
dataframe[["Country", "Age"]]

Country   Age
0   France  44.0
1    Spain  27.0
2  Germany  30.0
3    Spain  38.0
4  Germany  40.0
5   France  35.0
6    Spain   NaN
7   France  48.0
8  Germany  50.0
9   France  37.0

### Label indexing using iloc

The iloc indexer syntax is ``data.iloc[<row selection>, <column selection>]``, which is sure to be a source of confusion for R users. “iloc” in pandas is used to select rows and columns by number, in the order that they appear in the data frame.

In [47]:
dataframe.iloc[0]

Country      France
Age              44
Salary        72000
Purchased        No
Name: 0, dtype: object

In [48]:
dataframe.iloc[0, 1]

44.0

In [49]:
dataframe.iloc[0:2,1:3]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0

In [50]:
# saving the dataframe 
dataframe.to_csv('file1.csv', index=False)